general:
  kiosk-mode: full
  autofit: true
  lxde: false
  lxde-home: /home/pi
  window-position: 1920,1000

target:
  login-method: anon
  username: user
  password: changeme
  playlist: false
  use-mfa: false
  URL: https://play.grafana.org
  ignore-certificate-errors: false

goauth:
  auto-login: false
  fieldname-username: username
  fieldname-password: password
