general:
  mode: full
  autofit: true
  lxde: true
  lxde-home: /home/pi

target:
  login-method: anon
  username: user
  password: changeme
  playlist: false
  url: https://play.grafana.org
  ignore-certificate-errors: false
