name: Spell Check

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - '**.go'
      - 'cspell.config.json'
  pull_request:
    paths:
      - '**.md'
      - '**.go'
      - 'cspell.config.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  cspell:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: streetsidesoftware/cspell-action@6f3c77c1406bc930f944ba97e9801a22e42caf58 # v9.1.0
        with:
          config: cspell.config.json
