name: Markdown Lint

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - '.markdownlint-cli2.yaml'
  pull_request:
    paths:
      - '**.md'
      - '.markdownlint-cli2.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: DavidAnson/markdownlint-cli2-action@6b51ade7a9e4a75a7ad929842dd298a3804ebe8b # v23.1.0
        with:
          config: .markdownlint-cli2.yaml
